### ISSUE TITLE
please see if you can add initial liquidity on https://verse.bitcoin.com/ using provided wallet address

### ISSUE THREAD

**Issue by Gutiman18** [bitcoin-portal/verse-dex-tokens#36]
Hello, I have access Verse using provided wallet, but when logging in I cant see my LP. Why?

**Comment by Gutiman18** [comment]
With Brave Browser I can access wallet history, and see my LP provided. Strange others browser cant, but true.

**Comment by Scrapz7** [comment]
me too please
